package it.mdg.apiRest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import it.mdg.apiRest.entity.Student;

import java.util.List;


@Service
public class StudentService {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private StudentRepository studentRepository;

  

   public Student saveProduct(Student student) {
       return studentRepository.save(student);
   }

/*
   public Product getProduct(long productId) {
       return productRepository.findById(productId).orElseThrow(() -> new RuntimeException("Not Found"));
   }


   public List<Product> getProducts() {
       return productRepository.findAll();
   }*/


   public Student updateStudent(long productId, Student student) {
	   
       Student existingStudent = studentRepository.findById((int) productId).orElseThrow(() -> new RuntimeException("Not Found"));
       
       existingStudent.setFirstName(student.getFirstName());
       existingStudent.setLastName(student.getLastName());
       existingStudent.setEmail(student.getEmail());
      
       studentRepository.save(existingStudent);
       
       return existingStudent;
   }


   public Student deleteStudent(long studentId) {
       Student existingStudent = studentRepository.findById((int) studentId).orElseThrow(() -> new RuntimeException("Not Found"));
       studentRepository.deleteById((int) studentId);
       return existingStudent;
   }

/*
   public List<Product> getProductsByName(String productName) {
       return productRepository.getProductsByName(productName);
   }*/
}

